server:
  port: 8763
spring:
  application:
    name: cloud-authen
  output:
    ansi:
      enabled: detect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
logging:
  level:
    root: info
    com.microservice.cloud.authen: info



