server:
  port: 9000
spring:
  application:
    name: cloud-gateway
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: info
    com.microservice.cloud: info
    org.springframework.cloud.gateway: debug
zuul:
  routes:
    cloud-user:
      path: /user/**
      serviceId: cloud-user
    cloud-authen:
      path: /auth/**
      serviceId: cloud-authen